module.exports = {
  builtAt: false,
  cached: true,
  cachedAssets: true,
  chunkModules: true,
  chunkOrigins: true,
  colors: true,
  depth: true,
  entrypoints: true,
  errorDetails: true,
  exclude: [/node_modules/],
  hash: false,
  modules: false,
  warnings: true,
}
