module.exports = {
  packageJson: {
    scripts: {
      prettier: 'prettier "*/**/*.{js,jsx,ts,tsx,json,md}" --write',
      build: 'gnarly-app-build',
      'build-static': 'gnarly-app-build & gnarly-app-build-static',
      dev: 'gnarly-app-dev',
      start: 'gnarly-app-serve',
      tslint: 'tslint -p tsconfig.json -c ./tslint.json "./src/**/*.ts?(x)"',
    },
    'pre-commit': ['tslint'],
  },
  deps: [
    // '@gnarlycode/react-route-fetch',
    '@gnarlycode/react-scroll-state',
    // '@gnarlycode/react-styled-css-transition',
    'is-in-browser',
    'express',
    'react',
    'react-dom',
    'react-helmet',
    'react-hot-loader',
    // 'react-redux',
    'react-router',
    'react-router-config',
    'react-router-dom',
    // 'react-transition-group',
    // 'recompose',
    // 'redux',
    'styled-components',
  ],
  devDeps: [
    '@gnarlycode/tslint-config',
    '@types/express',
    '@types/react',
    '@types/react-dom',
    '@types/react-helmet',
    // '@types/react-redux',
    '@types/react-router',
    '@types/react-router-config',
    '@types/react-router-dom',
    '@types/styled-components',
    // '@types/react-transition-group',
    // '@types/recompose',
    'pre-commit',
    'redux-logger',
    'tslint',
  ],
}
