module.exports = {
  packageJson: {
    scripts: {
      prettier: 'prettier "./**/*.{js,jsx,ts,tsx,json,md}" --write',
      eslint: 'eslint --ext .jsx,.js,.tsx,.ts ./',
      build: 'gnarly-app-build',
      'build-static': 'gnarly-app-build && gnarly-app-build-static',
      dev: 'gnarly-app-dev',
      start: 'gnarly-app-serve',
      analyze: 'gnarly-app-analyze',
    },
    husky: {
      hooks: {
        'pre-commit': 'lint-staged',
      },
    },
    'lint-staged': {
      '*.{js,jsx,ts,tsx}': ['prettier --write', 'eslint', 'git add'],
      '*.{json,css,md}': ['prettier --write', 'git add'],
    },
  },
  deps: [
    'astroturf',
    'classnames',
    'cross-fetch',
    'is-in-browser',
    'express',
    'react',
    'react-dom',
    'react-helmet-async',
    'react-hot-loader',
    'react-router',
    'react-router-config',
    'react-router-dom',
    'react-transition-group',
  ],
  devDeps: [
    '@types/classnames',
    '@types/express',
    '@types/react',
    '@types/react-dom',
    '@types/react-helmet',
    '@types/react-router',
    '@types/react-router-config',
    '@types/react-router-dom',
    '@types/react-transition-group',
    '@typescript-eslint/parser',
    '@typescript-eslint/eslint-plugin',
    'eslint',
    'eslint-config-prettier',
    'eslint-plugin-babel',
    'eslint-plugin-prettier',
    'eslint-plugin-react',
    'husky',
    'lint-staged',
  ],
}
